# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 04:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u041e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0435\u043c\u043e\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u043b\u043e\u044f', max_length=50, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('app', models.CharField(default='dynamit', max_length=50)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('change_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u044f')),
                ('slug', models.SlugField(help_text='\u041e\u0431\u043e\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 \u0432 \u0430\u0434\u0440\u0435\u0441\u043d\u043e\u0439 \u0441\u0442\u0440\u043e\u043a\u0435. \u041b\u0430\u0442\u0438\u043d\u0441\u043a\u0438\u043c\u0438 \u0431\u0443\u043a\u0432\u0430\u043c\u0438', verbose_name='\u041f\u0443\u0442\u044c')),
                ('description', models.TextField(blank=True, help_text='\u041f\u043e\u0434\u0440\u043e\u0431\u043d\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0441\u043b\u043e\u044f', null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('is_public', models.BooleanField(default=False, verbose_name='\u041f\u0443\u0431\u043b\u0438\u0447\u043d\u044b\u0439 \u0441\u043b\u043e\u0439')),
                ('can_comment', models.BooleanField(default=False, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0438')),
                ('photo_gallery', models.BooleanField(default=False, verbose_name='\u0424\u043e\u0442\u043e\u0433\u0430\u043b\u0435\u0440\u0435\u044f')),
                ('entryname', models.CharField(blank=True, default='id', help_text='\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u043a\u043e\u043b\u043e\u043d\u043a\u0443, \u043a\u043e\u0442\u043e\u0440\u0443\u044e \u0431\u0443\u0434\u0435\u0442\u0435 \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u0434\u043b\u044f \u043e\u0431\u043e\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u044f \u0437\u0430\u043f\u0438\u0441\u0435\u0439', max_length=50, null=True, verbose_name='\u041e\u0431\u043e\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 \u0437\u0430\u043f\u0438\u0441\u0435\u0439')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u0414\u0438\u043d\u0430\u043c\u0438\u0447\u0435\u0441\u043a\u0430\u044f \u043c\u043e\u0434\u0435\u043b\u044c',
                'verbose_name_plural': '\u0414\u0438\u043d\u0430\u043c\u0438\u0447\u0435\u0441\u043a\u0438\u0435 \u043c\u043e\u0434\u0435\u043b\u0438',
            },
        ),
        migrations.CreateModel(
            name='DynamitModelField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u043e\u043b\u043e\u043d\u043a\u0438 \u0432 \u0431\u0430\u0437\u0435 \u0434\u0430\u043d\u043d\u044b\u0445', verbose_name='\u0421\u0438\u0441\u0442\u0435\u043c\u043d\u043e\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('verbose_name', models.CharField(help_text='\u041e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0435\u043c\u043e\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435', max_length=50, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('field_type', models.CharField(choices=[('Basic Fields', [('dynamicfloatfield', 'FloatField'), ('dynamiccharfield', 'CharField'), ('dynamictextfield', 'TextField'), ('dynamicdatetimefield', 'DateTimeField'), ('dynamicemailfield', 'EmailField'), ('dynamicpositiveintegerfield', 'PositiveIntegerField'), ('dynamicintegerfield', 'IntegerField'), ('dynamicurlfield', 'UrlField'), ('dynamicbooleanfield', 'BooleanField'), ('dynamicdatefield', 'DateField'), ('dynamictimefield', 'TimeField')])], max_length=128, verbose_name='\u0422\u0438\u043f')),
                ('null', models.BooleanField(default=True, help_text='\u041c\u043e\u0436\u0435\u0442 \u0441\u043e\u0434\u0435\u0440\u0436\u0430\u0442\u044c "null" \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u044f?', verbose_name='Null')),
                ('blank', models.BooleanField(default=True, help_text='\u041c\u043e\u0436\u0435\u0442 \u0431\u044b\u0442\u044c \u043f\u0443\u0441\u0442\u044b\u043c?', verbose_name='Blank')),
                ('unique', models.BooleanField(default=False, verbose_name='Unique')),
                ('default', models.CharField(blank=True, max_length=32, null=True, verbose_name='Default value')),
                ('help_text', models.CharField(blank=True, help_text="Short description of the field' purpose", max_length=256, null=True, verbose_name='Help Text')),
                ('order', models.IntegerField(verbose_name='\u041f\u043e\u0437\u0438\u0446\u0438\u044f \u043f\u043e\u043b\u044f')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='dynamit.DynamitModel')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': 'Dynamic Model Field',
            },
        ),
        migrations.AlterUniqueTogether(
            name='dynamitmodelfield',
            unique_together=set([('model', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='dynamitmodel',
            unique_together=set([('user', 'slug')]),
        ),
    ]
